language: android
android:
 components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk: oraclejdk8

script: ./gradlew testDebug
deploy:
    provider: release
    api_key:
  file: k9mail/build/outputs/apk/k9mail-debug.apk
  on:
    repo: winardiaris/k-9
    tags: true


